### PR TITLE
Fix panic if too many instances are unavailable

### LINKED ISSUE #313: pkcs11/src/backend/login.rs crashes with index out of bounds
Hi,

we have recently observed errors like the following:

```txt
thread '<unnamed>' panicked at pkcs11/src/backend/login.rs:243:48:
index out of bounds: the len is 3 but the index is 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This occurs when `keymgr` (a utility for the knot nameserver) tries to communicate with the configured pkcs11-backend, `nethsm-pkcs11` in our case.

We run a cluster of 3 nethsms.

I have roughly 0 amount of experience in rust, but it looks to me like there should be a modulo operator somewhere (?):

```rust
        for i in 0..self.slot.instances.len() - 1 {
            let instance = &self.slot.instances[index + i];
            ...
        }
```

(from [`pkcs11/src/backend/login.rs:243`](https://github.com/Nitrokey/nethsm-pkcs11/blob/7fba23ea53c0aa9dabcf1f4cdc18fc4927e52c97/pkcs11/src/backend/login.rs#L243))

I might very well be completely off, in which case I'd appreciate a gentle hit with the clue-bat...

Of course we can also try and run with `RUST_BACKTRACE=1`, it is just that this error occurs rather infrequently (but when it occurs, it occurs multiple times in a row and crashes `keymgr` in the process) and we'd probably need to wait a few days / weeks to see it again.

Our (redacted) pks11-config looks like this:

```conf
enable_set_attribute_value: false

log_level: Info

syslog_socket: /apperently/broken/lol
syslog_facility: "user"

log_file: /path/to/p11nethsm.log

slots:
  - label: nethsm
    description: foo

    operator:
      username: "operator"
      password: "some-password"
    instances:
      - url: "https://hsm-instance-1.example.com:443/api/v1"
        max_idle_connections: 10
      - url: "https://hsm-instance-2.example.com:443/api/v1"
        max_idle_connections: 10
      - url: "https://hsm-instance-3.example.com:443/api/v1"
        max_idle_connections: 10

    certificate_format: PEM

    retries:
      count: 3
      delay_seconds: 1

    tcp_keepalive:
      time_seconds: 600
      interval_seconds: 60
      retries: 3

    connections_max_idle_duration: 1800

    timeout_seconds: 10
```

And at the time we observe the above error, we find this in the log (repeated 3 times - after which we see no more logs, so _probably_ `keymgr` has crashed and does not try to access the nethsm anymore):

```log
INFO  nethsm_pkcs11::config::logging] Loaded config file at: /path/to/p11nethsm.conf
INFO  nethsm_pkcs11::config::logging] Logging to File /path/to/p11nethsm.log
WARN  nethsm_pkcs11::config::logging] Could not open SYSLOG socket
INFO  nethsm_pkcs11::config::initialization] Loaded configuration with 1 slots
INFO  nethsm_pkcs11::config::initialization] Slot with 3 instances, timeout: Some(10), retries: Some(RetryConfig { count: 3, delay_seconds: 1 })
INFO  nethsm_pkcs11::config::initialization] Instance configured with: max_idle_connection: Some(10)
INFO  nethsm_pkcs11::config::initialization] Instance configured with: max_idle_connection: Some(10)
INFO  nethsm_pkcs11::config::initialization] Instance configured with: max_idle_connection: Some(10)
WARN  nethsm_pkcs11::backend::login] Connection attempt 1 failed: IO error connecting to the instance, timeout: global, retrying in 1s
WARN  nethsm_pkcs11::backend::login] Connection attempt 1 failed: IO error connecting to the instance, timeout: global, retrying in 1s
WARN  nethsm_pkcs11::backend::login] Connection attempt 2 failed: IO error connecting to the instance, timeout: global, retrying in 1s
```

Please let me know if I can provide any additional information for troubleshooting :)

### PR DESCRIPTION
**Pull request by robin-nitrokey**
This fixes a regression from https://github.com/Nitrokey/nethsm-pkcs11/pull/218: The current implementation does not calculate the index correctly when looping over the available instances. This can be fixed by replacing the index with an iterator. The old loop also skipped the last instance because ranges are exclusive, so `for i in 0..self.slot.instances.len() - 1` yields values with `i < self.slot.instances.len() - 1`. I think this was an oversight and fixed it with this PR.

Fixes: https://github.com/Nitrokey/nethsm-pkcs11/issues/313

### CODE REVIEW

File: pkcs11/src/backend/login.rs [hunk 1]
```diff
@@ -239,9 +240,8 @@ impl LoginCtx {
                 return (instance, ShouldHealthCheck::HealthCheckFirst)
             }
         }
-        for i in 0..self.slot.instances.len() - 1 {
-            let instance = &self.slot.instances[index + i];
-
+        let (head, tail) = self.slot.instances.split_at(index);
+        for (i, instance) in iter::chain(tail, head).enumerate() {
             match (instance.should_try(), threads_allowed, accept_health_check) {
```
Comment (sosthene-nitrokey) [inline pkcs11/src/backend/login.rs:238]: The fact that it skips one instance is intentional because there is a "fast path" just above that already tests the first instance. So the fix should just be adding a modulo `self.slot.instances.len()`.

But you're right that we could remove this fast path that brings nothing (I don't really know why it was there in the first place).

```rust
    fn next_instance(
        &self,
        accept_health_check: HealthCheck,
    ) -> (&InstanceData, ShouldHealthCheck) {
        let threads_allowed = THREADS_ALLOWED.load(Relaxed);
        let index = self.slot.instance_balancer.load(Relaxed);
        let (head, tail) = self
            .slot
            .instances
            .split_at((index + 1) % self.slot.instances.len());
        for (i, instance) in tail.iter().chain(head).enumerate() {
            let i = i + 1;
            match (instance.should_try(), threads_allowed, accept_health_check) {
                (InstanceAttempt::Failed, _, _)
                | (InstanceAttempt::Retry, true, _)
                | (InstanceAttempt::Retry, false, HealthCheck::Avoid) => continue,
                (InstanceAttempt::Working, _, _) => {
                    // This not true round-robin in case of multithreaded acces
                    // This is degraded mode so best-effort is attempted at best
                    self.slot.instance_balancer.fetch_add(i, Relaxed);
                    return (instance, ShouldHealthCheck::RunDirectly);
                }
                (InstanceAttempt::Retry, false, HealthCheck::Possible) => {
                    // This not true round-robin in case of multithreaded acces
                    // This is degraded mode so best-effort is attempted at best
                    self.slot.instance_balancer.fetch_add(i, Relaxed);
                    return (instance, ShouldHealthCheck::HealthCheckFirst);
                }
            }
        }

        // No instance is valid, return a failed instance for an attempt
        let index = self.slot.instance_balancer.fetch_add(1, Relaxed);
        let index = index % self.slot.instances.len();
        // Instance is not valid, don't try health check, it would only slow things down
        (&self.slot.instances[index], ShouldHealthCheck::RunDirectly)
    }

```

**Review by sosthene-nitrokey — CHANGES_REQUESTED** [review]

File: pkcs11/src/backend/login.rs (hunk 1 above)
Comment (robin-nitrokey) [reply pkcs11/src/backend/login.rs:238]: > The fact that it skips one instance is intentional because there is a "fast path" just above that already tests the first instance.

But shouldn’t it skip the first instance instead of the last?

Comment (sosthene-nitrokey) [reply pkcs11/src/backend/login.rs:238]: Yeah the logic of this function didn't make the most sense, it should be simplified into just the loop like I did in the code just above.

Comment (robin-nitrokey) [reply pkcs11/src/backend/login.rs:238]: Updated.

**Review by sosthene-nitrokey — COMMENTED** [review]
LGTM, I think we should try to make have https://github.com/Nitrokey/nethsm-pkcs11/pull/315 before the release though, if I don't have something by noon we'll disable threads on windows for now.

**Comment by robin-nitrokey** [comment]
Okay, I’ve dropped the release commit from this PR so that we can merge it already.

**Review by sosthene-nitrokey — APPROVED** [review]
